csv_file 1.csv has 248324 rows, legal rows are 1821547
Traceback (most recent call last):
  File "form_record_group_data.py", line 78, in form_brand_record
    brand_no, apply_date, i18n_type, brand_status = analysis_row_end(line)
  File "form_record_group_data.py", line 164, in analysis_row_end
    apply_date = time.strptime(line[-3], date_origi_format)
  File "/usr/lib64/python2.7/_strptime.py", line 467, in _strptime_time
    return _strptime(data_string, format)[0]
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%Y\xe5\xb9\xb4%m\xe6\x9c\x88%d\xe6\x97\xa5'

Traceback (most recent call last):
  File "form_record_group_data.py", line 78, in form_brand_record
    brand_no, apply_date, i18n_type, brand_status = analysis_row_end(line)
  File "form_record_group_data.py", line 164, in analysis_row_end
    apply_date = time.strptime(line[-3], date_origi_format)
  File "/usr/lib64/python2.7/_strptime.py", line 467, in _strptime_time
    return _strptime(data_string, format)[0]
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%Y\xe5\xb9\xb4%m\xe6\x9c\x88%d\xe6\x97\xa5'

csv_file 2.csv has 260440 rows, legal rows are 1262733
/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py:105: Warning: Data truncated for column 'brand_name' at row 30
  rowcount = cursor.executemany(statement, parameters)
Traceback (most recent call last):
  File "form_record_group_data.py", line 78, in form_brand_record
    brand_no, apply_date, i18n_type, brand_status = analysis_row_end(line)
  File "form_record_group_data.py", line 164, in analysis_row_end
    apply_date = time.strptime(line[-3], date_origi_format)
  File "/usr/lib64/python2.7/_strptime.py", line 467, in _strptime_time
    return _strptime(data_string, format)[0]
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%Y\xe5\xb9\xb4%m\xe6\x9c\x88%d\xe6\x97\xa5'

Traceback (most recent call last):
  File "form_record_group_data.py", line 78, in form_brand_record
    brand_no, apply_date, i18n_type, brand_status = analysis_row_end(line)
  File "form_record_group_data.py", line 164, in analysis_row_end
    apply_date = time.strptime(line[-3], date_origi_format)
  File "/usr/lib64/python2.7/_strptime.py", line 467, in _strptime_time
    return _strptime(data_string, format)[0]
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%Y\xe5\xb9\xb4%m\xe6\x9c\x88%d\xe6\x97\xa5'

/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py:105: Warning: Data truncated for column 'brand_name' at row 51
  rowcount = cursor.executemany(statement, parameters)
/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py:105: Warning: Data truncated for column 'brand_name' at row 48
  rowcount = cursor.executemany(statement, parameters)
Traceback (most recent call last):
  File "form_record_group_data.py", line 93, in form_brand_record
    product_no_set = get_product_no_list(product_list_array, item_dict)
  File "form_record_group_data.py", line 145, in get_product_no_list
    product_group = int(product_list_array[index]['product_group'])
ValueError: invalid literal for int() with base 10: '0735;0736;0742'

Traceback (most recent call last):
  File "form_record_group_data.py", line 93, in form_brand_record
    product_no_set = get_product_no_list(product_list_array, item_dict)
  File "form_record_group_data.py", line 145, in get_product_no_list
    product_group = int(product_list_array[index]['product_group'])
ValueError: invalid literal for int() with base 10: '2803-2807'

/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py:105: Warning: Incorrect integer value: '' for column 'brand_status' at row 48
  rowcount = cursor.executemany(statement, parameters)
/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py:105: Warning: Incorrect integer value: '' for column 'brand_status' at row 49
  rowcount = cursor.executemany(statement, parameters)
/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py:105: Warning: Incorrect integer value: '' for column 'brand_status' at row 50
  rowcount = cursor.executemany(statement, parameters)
/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py:105: Warning: Incorrect integer value: '' for column 'brand_status' at row 51
  rowcount = cursor.executemany(statement, parameters)
/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py:105: Warning: Incorrect integer value: '' for column 'brand_status' at row 52
  rowcount = cursor.executemany(statement, parameters)
/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py:105: Warning: Incorrect integer value: '' for column 'brand_status' at row 53
  rowcount = cursor.executemany(statement, parameters)
/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py:105: Warning: Incorrect integer value: '' for column 'brand_status' at row 54
  rowcount = cursor.executemany(statement, parameters)
/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py:105: Warning: Incorrect integer value: '' for column 'brand_status' at row 55
  rowcount = cursor.executemany(statement, parameters)
/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py:105: Warning: Incorrect integer value: '' for column 'brand_status' at row 56
  rowcount = cursor.executemany(statement, parameters)
/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py:105: Warning: Incorrect integer value: '' for column 'brand_status' at row 57
  rowcount = cursor.executemany(statement, parameters)
/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py:105: Warning: Data truncated for column 'brand_name' at row 78
  rowcount = cursor.executemany(statement, parameters)
/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py:105: Warning: Data truncated for column 'brand_name' at row 79
  rowcount = cursor.executemany(statement, parameters)
/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py:105: Warning: Data truncated for column 'brand_name' at row 80
  rowcount = cursor.executemany(statement, parameters)
/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py:105: Warning: Data truncated for column 'brand_name' at row 81
  rowcount = cursor.executemany(statement, parameters)
/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py:105: Warning: Data truncated for column 'brand_name' at row 82
  rowcount = cursor.executemany(statement, parameters)
/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py:105: Warning: Data truncated for column 'brand_name' at row 83
  rowcount = cursor.executemany(statement, parameters)
/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py:105: Warning: Data truncated for column 'brand_name' at row 84
  rowcount = cursor.executemany(statement, parameters)
/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py:105: Warning: Data truncated for column 'brand_name' at row 85
  rowcount = cursor.executemany(statement, parameters)
/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py:105: Warning: Data truncated for column 'brand_name' at row 86
  rowcount = cursor.executemany(statement, parameters)
/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py:105: Warning: Data truncated for column 'brand_name' at row 87
  rowcount = cursor.executemany(statement, parameters)
Traceback (most recent call last):
  File "form_record_group_data.py", line 78, in form_brand_record
    brand_no, apply_date, i18n_type, brand_status = analysis_row_end(line)
  File "form_record_group_data.py", line 164, in analysis_row_end
    apply_date = time.strptime(line[-3], date_origi_format)
  File "/usr/lib64/python2.7/_strptime.py", line 467, in _strptime_time
    return _strptime(data_string, format)[0]
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%Y\xe5\xb9\xb4%m\xe6\x9c\x88%d\xe6\x97\xa5'

Traceback (most recent call last):
  File "form_record_group_data.py", line 78, in form_brand_record
    brand_no, apply_date, i18n_type, brand_status = analysis_row_end(line)
  File "form_record_group_data.py", line 164, in analysis_row_end
    apply_date = time.strptime(line[-3], date_origi_format)
  File "/usr/lib64/python2.7/_strptime.py", line 467, in _strptime_time
    return _strptime(data_string, format)[0]
  File "/usr/lib64/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%Y\xe5\xb9\xb4%m\xe6\x9c\x88%d\xe6\x97\xa5'

/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py:105: Warning: Data truncated for column 'brand_name' at row 33
  rowcount = cursor.executemany(statement, parameters)
Traceback (most recent call last):
  File "form_record_group_data.py", line 93, in form_brand_record
    product_no_set = get_product_no_list(product_list_array, item_dict)
  File "form_record_group_data.py", line 145, in get_product_no_list
    product_group = int(product_list_array[index]['product_group'])
ValueError: invalid literal for int() with base 10: '0807-0808'

csv_file 3.csv has 665116 rows, legal rows are 4180727
